NOT_APPLICABLE = "Not_Applicable"
DYNAMIC = "Dynamic"

"""
    PRODUCT POSITIONING CONSTANT
"""
PRODUCT_POSITIONING_UPSELL = "Upsell"
PRODUCT_POSITIONING_DOWNSELL = "Downsell"
PRODUCT_POSITIONING_USER_SELECTED = "User Selected"

"""
    PRODUCT GROUPING CONSTANT
"""
PRODUCT_GROUPING_BUNDLE_ID = "Bundle Id"
PRODUCT_GROUPING_NO_GROUPING = "No Grouping"

"""
    PRODUCT FULFILLMENT CONSTANT
"""
PRODUCT_FULFILLMENT_BRANCH = "Branch"
PRODUCT_FULFILLMENT_ESIG = "ESIG"
PRODUCT_FULFILLMENT_RDC = "RDC"
PRODUCT_FULFILLMENT_DIRECT = "DIRECT"





